### ISSUE TITLE
should match more comments, like FIXME

### ISSUE THREAD

**Issue by maxjacobson** [maxjacobson/todo_lint#1]
Right now it only matches lines with TODO, there are a few other significant things

**Comment by CalQL8ed-K-OS** [comment]
i could handle this if you point me in the right direction

**Comment by maxjacobson** [comment]
Hey, thanks!

In theory it should be as simple as changing this line https://github.com/maxjacobson/todo_lint/blob/master/lib/todo_lint/todo.rb#L6

From like `TODO` to `TODO|FIXME` but I'm not sure if any complications will arise. Check out the specs and see if there's anything to

**Comment by CalQL8ed-K-OS** [comment]
I'll try to do it TTD and I'll let you know what happens and if I get stuck

**Comment by maxjacobson** [comment]
Sounds great :smile:
